name: Analyze Unused Code

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  analyze-unused:
    name: Run unused exports & dependency analysis (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Install dependencies
        run: npm ci

      - name: Run unused code analysis
        run: |
          chmod +x ./scripts/analyze-unused.sh
          ./scripts/analyze-unused.sh
        continue-on-error: true

      - name: Upload analysis reports
        uses: actions/upload-artifact@v3
        with:
          name: unused-code-reports
          path: analysis/report-*.md

      - name: Build inline summary (best-effort)
        if: github.event_name == 'pull_request'
        id: summary
        run: |
          REPORT_FILE=$(ls -1 analysis/report-*.md 2>/dev/null | head -n1 || true)
          if [ -z "$REPORT_FILE" ]; then
            echo "report_body=No report markdown generated." >> $GITHUB_OUTPUT
            exit 0
          fi
          # Extract top section (up to first blank line after a heading block) and limit lines
            awk 'NR==1, /^$/ {print}' "$REPORT_FILE" | head -n 40 > /tmp/summary.md
          # Basic sanitization for GitHub comment body
          ESCAPED=$(sed 's/`/\\`/g' /tmp/summary.md)
          echo "report_body<<'EOF'" >> $GITHUB_OUTPUT
          echo "$ESCAPED" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Comment on PR with analysis report summary
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Unused Code Analysis Report
            Results for Node.js versions tested: 16, 18, 20.

            <details><summary>Summary (first report excerpt)</summary>

            ${{ steps.summary.outputs.report_body }}

            </details>

            Full reports are available as workflow artifacts (unused-code-reports). If new unused exports were introduced, this PR should adjust code or intentionally update the baseline.
      
      - name: Fail job if unused exports baseline check failed
        if: failure()
        run: exit 1
