name: Nightly Full Typecheck

on:
  schedule:
    - cron: '0 5 * * *' # 05:00 UTC daily
  workflow_dispatch:

permissions:
  contents: read

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps (ci)
        run: npm ci
      - name: Full TypeScript check
        id: tsc
        run: |
          set -o pipefail
          npm run check 2>&1 | tee full-typecheck.log
      - name: Upload log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: full-typecheck-log
          path: full-typecheck.log
      - name: Fail if errors present
        run: |
          if grep -E "error TS[0-9]+" full-typecheck.log; then
            echo 'Type errors detected';
            exit 1;
          fi
          echo 'No type errors.'
